"""Garde-fou des migrations Alembic.

Ces tests font échouer la suite le jour où un modèle change SANS migration
correspondante : avec Alembic, un oubli est silencieux (l'app démarre, puis
échoue en production sur une colonne absente). Chaque test migre sa PROPRE base
SQLite en mémoire, injectée via `config.attributes["connection"]` (cf.
alembic/env.py) : ni fichier, ni variable d'environnement, ni contact avec
cockpit.db.

Limite assumée : ils tournent sur SQLite. Les particularités PostgreSQL (types
enum natifs) ne sont pas exercées ici ; elles se vérifient à la main sur une base
PostgreSQL avant déploiement.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.pool import StaticPool

BACKEND_DIR = Path(__file__).resolve().parent.parent


def _alembic_config(connection=None) -> Config:
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    # Chemin absolu : indépendant du dossier depuis lequel pytest est lancé.
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    if connection is not None:
        config.attributes["connection"] = connection
    return config


@pytest.fixture
def migration_engine():
    """Base SQLite en mémoire, vierge, propre au test (StaticPool : une seule base
    partagée entre connexions)."""
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    yield engine
    engine.dispose()


def test_migrations_have_a_single_head():
    """Deux têtes = deux branches de migrations concurrentes : `upgrade head`
    serait ambigu. Se produit quand deux révisions partent de la même parente."""
    heads = ScriptDirectory.from_config(_alembic_config()).get_heads()
    assert len(heads) == 1, f"Plusieurs têtes de migration : {heads}"


def test_migrations_build_the_schema_declared_by_models(migration_engine):
    """`upgrade head` depuis une base VIDE doit produire exactement le schéma des
    modèles : `check` échoue (AutogenerateDiffsDetected) au moindre écart.

    C'est LE test qui attrape « j'ai changé models.py sans écrire de migration »."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "head")
        command.check(config)


def _seed_applications(connection, statuses: list[str]) -> None:
    """Insère un utilisateur, un tableau et une candidature par statut, en SQL brut.

    SQL brut et non les modèles : la base est au niveau de schéma d'une révision
    donnée, qui n'est pas forcément celui des modèles actuels. Les statuts sont
    des NOMS de membres (`SAVED`), comme SQLAlchemy les stocke."""
    now = "2026-01-01 00:00:00"
    connection.execute(
        text(
            "INSERT INTO users (email, hashed_password, is_verified, created_at) "
            f"VALUES ('seed@example.com', 'x', 1, '{now}')"
        )
    )
    connection.execute(
        text(
            "INSERT INTO boards (name, user_id, created_at, updated_at) "
            f"VALUES ('B', 1, '{now}', '{now}')"
        )
    )
    for index, status in enumerate(statuses):
        connection.execute(
            text(
                "INSERT INTO applications "
                "(title, company, source, status, board_id, created_at, updated_at) "
                f"VALUES ('t{index}', 'c', 'manual', '{status}', 1, '{now}', '{now}')"
            )
        )


def _stored_statuses(connection) -> list[str]:
    rows = connection.execute(text("SELECT status FROM applications ORDER BY id"))
    return [row[0] for row in rows]


def test_migration_0002_refuses_to_run_while_rejected_rows_exist(migration_engine):
    """GARDE-FOU de la migration 0002 : une ligne REJECTED interrompt l'upgrade
    avec un message explicite, et la révision reste à 0001.

    Seule partie de 0002 protégée automatiquement : le DDL PostgreSQL (recréation
    du type enum) n'est PAS exercé ici, et `alembic check` ne compare pas les
    libellés d'un enum. Il se vérifie à la main sur un PostgreSQL jetable."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0001")
        _seed_applications(connection, ["SAVED", "REJECTED"])

        with pytest.raises(RuntimeError, match="REJECTED"):
            command.upgrade(config, "head")

        assert _stored_statuses(connection) == ["SAVED", "REJECTED"]
        version = connection.execute(text("SELECT version_num FROM alembic_version"))
        assert version.scalar_one() == "0001"


def test_migration_0002_keeps_every_row_in_both_directions(migration_engine):
    """Sans ligne REJECTED, l'upgrade passe et le downgrade aussi : aucune
    candidature n'est modifiée ni perdue, dans un sens comme dans l'autre."""
    statuses = ["SAVED", "APPLIED", "FOLLOWED_UP", "INTERVIEW", "ACCEPTED"]
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0001")
        _seed_applications(connection, statuses)

        command.upgrade(config, "head")
        assert _stored_statuses(connection) == statuses

        command.downgrade(config, "0001")
        assert _stored_statuses(connection) == statuses


def _seed_notes(connection, notes: list[str | None]) -> None:
    """Insère un utilisateur, un tableau et une candidature par note (SQL brut :
    la base est au niveau de schéma d'une révision donnée)."""
    _seed_applications(connection, ["SAVED"] * len(notes))
    for index, note in enumerate(notes, start=1):
        connection.execute(
            text("UPDATE applications SET notes = :note WHERE id = :id"),
            {"note": note, "id": index},
        )


def _stored_notes(connection) -> list[str | None]:
    rows = connection.execute(text("SELECT notes FROM applications ORDER BY id"))
    return [row[0] for row in rows]


def test_migration_0004_refuses_to_run_while_a_note_is_too_long(migration_engine):
    """GARDE-FOU de la migration 0004 : une note de 5001 caractères interrompt
    l'upgrade avec un message explicite, rien n'est tronqué, et la révision reste
    à 0003. Une note de 5000 caractères, elle, ne bloque pas.

    Seule partie de 0004 protégée ici : le DDL PostgreSQL (ALTER ... TYPE
    VARCHAR(5000)) n'est PAS exercé, SQLite n'applique pas les longueurs. Il se
    vérifie à la main sur un PostgreSQL jetable."""
    too_long = "x" * 5001
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0003")
        _seed_notes(connection, ["ok", too_long, "y" * 5000])

        with pytest.raises(RuntimeError, match=r"1 candidature\(s\).*5001"):
            command.upgrade(config, "0004")

        assert _stored_notes(connection) == ["ok", too_long, "y" * 5000]
        version = connection.execute(text("SELECT version_num FROM alembic_version"))
        assert version.scalar_one() == "0003"


def test_migration_0004_keeps_every_note_in_both_directions(migration_engine):
    """Sans note trop longue, l'upgrade passe et le downgrade aussi : aucune note
    n'est modifiée, tronquée ni perdue (NULL, vide et 5000 caractères compris)."""
    notes = [None, "", "court", "é" * 5000]
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0003")
        _seed_notes(connection, notes)

        command.upgrade(config, "0004")
        assert _stored_notes(connection) == notes

        command.downgrade(config, "0003")
        assert _stored_notes(connection) == notes


# Jeu de données de la 0005, au niveau de schéma 0004 (SQL brut) :
# (tableau, statut, updated_at, archivée). Deux tableaux, plusieurs statuts, des
# updated_at dans le désordre de l'id, une ÉGALITÉ d'updated_at et des archivées.
_ROWS_0005 = [
    (1, "SAVED", "2026-03-01 10:00:00", False),       # id 1
    (1, "SAVED", "2026-03-05 10:00:00", False),       # id 2
    (1, "SAVED", "2026-03-03 10:00:00", False),       # id 3
    (1, "SAVED", "2026-03-04 10:00:00", True),        # id 4 (archivée)
    (1, "APPLIED", "2026-03-02 10:00:00", False),     # id 5
    (1, "APPLIED", "2026-03-02 10:00:00", False),     # id 6 (égalité avec 5)
    (2, "SAVED", "2026-03-09 10:00:00", False),       # id 7
    (2, "SAVED", "2026-03-08 10:00:00", False),       # id 8
    (1, "SAVED", "2026-03-02 10:00:00", False),       # id 9
    (2, "INTERVIEW", "2026-03-01 10:00:00", True),    # id 10 (archivée)
]


def _seed_rows_0005(connection) -> None:
    now = "2026-01-01 00:00:00"
    connection.execute(
        text(
            "INSERT INTO users (email, hashed_password, is_verified, created_at) "
            f"VALUES ('seed@example.com', 'x', 1, '{now}')"
        )
    )
    for name in ("B1", "B2"):
        connection.execute(
            text(
                "INSERT INTO boards (name, user_id, created_at, updated_at) "
                f"VALUES ('{name}', 1, '{now}', '{now}')"
            )
        )
    for index, (board, status, updated_at, archived) in enumerate(_ROWS_0005, start=1):
        connection.execute(
            text(
                "INSERT INTO applications (title, company, source, status, board_id, "
                "archived_at, created_at, updated_at) VALUES (:t, 'c', 'manual', :s, :b, "
                ":a, :now, :u)"
            ),
            {
                "t": f"t{index}",
                "s": status,
                "b": board,
                "a": "2026-04-01 00:00:00" if archived else None,
                "now": now,
                "u": updated_at,
            },
        )


def _ordered_like_before_0005(connection) -> list[tuple]:
    """L'ordre affiché AVANT la 0005 : la requête de l'ancien list_applications
    (updated_at décroissant, actives seulement), regroupée par colonne. `id DESC`
    départage les égalités, que l'ancien tri laissait au hasard du moteur."""
    rows = connection.execute(
        text(
            "SELECT board_id, status, id FROM applications WHERE archived_at IS NULL "
            "ORDER BY board_id, status, updated_at DESC, id DESC"
        )
    )
    return [tuple(row) for row in rows]


def test_migration_0005_numbers_each_column_in_the_order_displayed_before(migration_engine):
    """Au déploiement, rien ne bouge à l'écran : dans chaque colonne (tableau,
    statut), les positions 0..n-1 suivent exactement l'ancien tri (updated_at
    décroissant, égalités départagées par id décroissant). Les archivées restent
    à NULL. Aucune autre colonne n'est modifiée (updated_at compris)."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0004")
        _seed_rows_0005(connection)
        expected_order = _ordered_like_before_0005(connection)
        before = connection.execute(text("SELECT * FROM applications ORDER BY id")).all()

        command.upgrade(config, "0005")

        rows = connection.execute(
            text(
                "SELECT board_id, status, id, position, archived_at FROM applications "
                "ORDER BY board_id, status, position"
            )
        ).all()
        active = [(r.board_id, r.status, r.id) for r in rows if r.archived_at is None]
        assert active == expected_order
        # Valeurs exactes, écrites en dur (indépendantes de la requête ci-dessus).
        positions = {r.id: r.position for r in rows}
        assert positions == {
            2: 0, 4: None, 3: 1, 9: 2, 1: 3,   # B1 SAVED (4 archivée)
            6: 0, 5: 1,                        # B1 APPLIED, égalité → id décroissant
            7: 0, 8: 1,                        # B2 SAVED
            10: None,                          # B2 INTERVIEW archivée
        }
        after = connection.execute(
            text(
                "SELECT id, title, company, location, url, source, status, notes, "
                "applied_at, archived_at, board_id, created_at, updated_at "
                "FROM applications ORDER BY id"
            )
        ).all()
        assert [tuple(r) for r in after] == [
            tuple(getattr(r, c) for c in (
                "id", "title", "company", "location", "url", "source", "status",
                "notes", "applied_at", "archived_at", "board_id", "created_at",
                "updated_at",
            ))
            for r in before
        ]


def test_migration_0005_downgrade_keeps_every_row(migration_engine):
    """Aller-retour : le downgrade retire la colonne (l'ordre choisi est perdu, c'est
    inhérent) sans perdre ni modifier aucune ligne ; la remontée renumérote."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "0004")
        _seed_rows_0005(connection)
        before = connection.execute(text("SELECT * FROM applications ORDER BY id")).all()

        command.upgrade(config, "0005")
        command.downgrade(config, "0004")
        assert "position" not in {c["name"] for c in inspect(connection).get_columns("applications")}
        assert connection.execute(text("SELECT * FROM applications ORDER BY id")).all() == before

        command.upgrade(config, "0005")
        numbered = connection.execute(
            text("SELECT count(*) FROM applications WHERE position IS NOT NULL")
        ).scalar_one()
        assert numbered == 8


def test_migrations_can_be_fully_downgraded(migration_engine):
    """Toute migration doit être réversible : `downgrade base` ne laisse aucune
    table applicative (seule la table de suivi d'Alembic subsiste)."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "head")
        command.downgrade(config, "base")
        remaining = set(inspect(connection).get_table_names())
    assert remaining <= {"alembic_version"}, f"Tables restantes : {remaining}"
