"""Garde-fou des migrations Alembic.

Ces tests font échouer la suite le jour où un modèle change SANS migration
correspondante : avec Alembic, un oubli est silencieux (l'app démarre, puis
échoue en production sur une colonne absente). Chaque test migre sa PROPRE base
SQLite en mémoire, injectée via `config.attributes["connection"]` (cf.
alembic/env.py) : ni fichier, ni variable d'environnement, ni contact avec
cockpit.db.

Limite assumée : ils tournent sur SQLite. Les particularités PostgreSQL (types
enum natifs) ne sont pas exercées ici ; elles se vérifient à la main sur une base
PostgreSQL avant déploiement.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect
from sqlalchemy.pool import StaticPool

BACKEND_DIR = Path(__file__).resolve().parent.parent


def _alembic_config(connection=None) -> Config:
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    # Chemin absolu : indépendant du dossier depuis lequel pytest est lancé.
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    if connection is not None:
        config.attributes["connection"] = connection
    return config


@pytest.fixture
def migration_engine():
    """Base SQLite en mémoire, vierge, propre au test (StaticPool : une seule base
    partagée entre connexions)."""
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    yield engine
    engine.dispose()


def test_migrations_have_a_single_head():
    """Deux têtes = deux branches de migrations concurrentes : `upgrade head`
    serait ambigu. Se produit quand deux révisions partent de la même parente."""
    heads = ScriptDirectory.from_config(_alembic_config()).get_heads()
    assert len(heads) == 1, f"Plusieurs têtes de migration : {heads}"


def test_migrations_build_the_schema_declared_by_models(migration_engine):
    """`upgrade head` depuis une base VIDE doit produire exactement le schéma des
    modèles : `check` échoue (AutogenerateDiffsDetected) au moindre écart.

    C'est LE test qui attrape « j'ai changé models.py sans écrire de migration »."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "head")
        command.check(config)


def test_migrations_can_be_fully_downgraded(migration_engine):
    """Toute migration doit être réversible : `downgrade base` ne laisse aucune
    table applicative (seule la table de suivi d'Alembic subsiste)."""
    with migration_engine.connect() as connection:
        config = _alembic_config(connection)
        command.upgrade(config, "head")
        command.downgrade(config, "base")
        remaining = set(inspect(connection).get_table_names())
    assert remaining <= {"alembic_version"}, f"Tables restantes : {remaining}"
