"""archive applications

Ajoute `applications.archived_at` (DateTime, nullable, sans valeur par défaut) :
NULL = candidature active, renseignée = archivée à cette date. Toutes les
lignes existantes valent NULL après cette migration, donc restent actives —
aucune donnée n'est réinterprétée. `ADD COLUMN` nullable sans défaut : une
opération de métadonnées sous PostgreSQL, quasi instantanée quelle que soit la
taille de la table ; SQLite la gère nativement (le mode batch d'Alembic
ci-dessous est systématique sous SQLite, cf. alembic/env.py, pas une
nécessité propre à cette colonne).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 16:31:24.092498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision, utilisés par Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
