"""baseline

Schéma tel que créé par l'ancien create_all() : c'est l'état de la production au
moment de l'adoption d'Alembic. En prod cette révision n'est JAMAIS exécutée : on
la marque appliquée avec `alembic stamp 0001`, après avoir vérifié que la base
réelle correspond. Elle ne sert à l'exécution que pour bâtir une base neuve
(dev, tests).

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 16:28:07.463692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision, utilisés par Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boards_user_id'), ['user_id'], unique=False)

    op.create_table('security_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Enum('PASSWORD_RESET', 'EMAIL_VERIFICATION', name='tokenpurpose'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_security_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'FOLLOWED_UP', 'INTERVIEW', 'REJECTED', 'ACCEPTED', name='applicationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_board_id'))

    op.drop_table('applications')
    with op.batch_alter_table('security_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_security_tokens_id'))

    op.drop_table('security_tokens')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_user_id'))
        batch_op.drop_index(batch_op.f('ix_boards_id'))

    op.drop_table('boards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

    # AJOUT MANUEL (non généré) : sous PostgreSQL, les enums sont des TYPES natifs
    # que drop_table ne supprime pas. Sans ces lignes, un downgrade suivi d'un
    # nouvel upgrade échouerait sur « type already exists ». Sans effet sous SQLite
    # (enum = VARCHAR), et checkfirst rend l'appel inoffensif si le type est absent.
    bind = op.get_bind()
    sa.Enum(name='applicationstatus').drop(bind, checkfirst=True)
    sa.Enum(name='tokenpurpose').drop(bind, checkfirst=True)
